// ***********************************************************************
// Assembly : VerizonConnect.BusinessSystemSolutionFinanceUI
// Author : Tyler Kraupp
// Created : 06-20-2019
//
// Last Modified By : Tyler Kraupp
// Last Modified On : 07-17-2019
// ***********************************************************************
// <copyright file="Program.cs" company="Verizon Connect">
// Verizon Connect
//// </copyright>

namespace VerizonConnect.BuSSFinanceUI
{
    using Microsoft.AspNetCore;
    using Microsoft.AspNetCore.Hosting;

    /// <summary>
    /// This is the program.cs file that is automatically generated by .NET Core and helps the app run
    /// </summary>
    public class Program
    {
        /// <summary>
        /// Initializes the program
        /// </summary>
        /// <param name="args">I believe these are the parameters to start the app based on settings</param>
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        /// <summary>
        /// Builds the web host
        /// </summary>
        /// <param name="args">I believe these are the parameters to start the app based on settings</param>
        /// <returns>Returns a startup object</returns>
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
}
